### ISSUE TITLE
More consistent examples

### ISSUE THREAD

**Issue by cesarcosta99** [metagrover/ES6-for-humans#42]
I've noticed you kept ES5 syntax in some given examples, e.g. functions instead of arrow functions. Was it on purpose? If it wasn't, I would be happy to contribute and rework the examples.

**Comment by metagrover** [comment]
Hi @cesarcosta99, thanks for bringing this into my attention. I guess, the functions in the Promises section can be rewritten as arrow functions. Feel free to modify and send in a PR.

Do let me know, if you feel there are more changes that can be done regarding this issue.

**Comment by cesarcosta99** [comment]
Hi @metagrover, no problem, I sent the PR. Please tell me if has something you disagree. BTW great repo, I'm happy to contribute to it :smiley:
